namespace SmartTVRelay.Core.Tests.Ingest;

using SmartTVRelay.Core.Ingest;
using System;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Xunit;

[Collection("Subprocess")]
public class CaptionExtractorTests
{
    private static string GetSyntheticFixturePath(string filename) =>
        Path.Combine(AppContext.BaseDirectory, "synthetic", filename);

    private static string GetCapturedFixturePath(string filename) =>
        Path.Combine(AppContext.BaseDirectory, "captures", filename);

    [Fact]
    public async Task ExtractAsync_WithSyntheticFixture_ReturnsExactlyTwoCaptionsWithExpectedTimingAndText()
    {
        // Arrange: fixtures/synthetic/captions-sample.mp4 is generated by
        // fixtures/synthetic/generate-captions-fixture.sh, embedding a "Hello from captions" cue
        // at 1.0-2.5s and a "Second caption line" cue at 3.0-4.2s (confirmed by hand-verifying
        // ffmpeg's actual WebVTT output against this fixture before writing this assertion).
        var extractor = new CaptionExtractor();
        var fixturePath = GetSyntheticFixturePath("captions-sample.mp4");
        Assert.True(File.Exists(fixturePath), $"Fixture file not found: {fixturePath}");

        // Act
        var samples = await extractor.ExtractAsync(fixturePath, CancellationToken.None);

        // Assert
        Assert.Equal(2, samples.Count);

        Assert.Equal("Hello from captions", samples[0].Text);
        Assert.Equal(DateTimeOffset.UnixEpoch + TimeSpan.FromSeconds(1.0), samples[0].StartTime);
        Assert.Equal(DateTimeOffset.UnixEpoch + TimeSpan.FromSeconds(2.5), samples[0].EndTime);

        Assert.Equal("Second caption line", samples[1].Text);
        Assert.Equal(DateTimeOffset.UnixEpoch + TimeSpan.FromSeconds(3.0), samples[1].StartTime);
        Assert.Equal(DateTimeOffset.UnixEpoch + TimeSpan.FromSeconds(4.2), samples[1].EndTime);
    }

    [Fact]
    public async Task ExtractAsync_NoSubtitleStream_ReturnsEmptyListWithoutThrowing()
    {
        // Arrange: the real HDHomeRun capture has video + 2 audio streams and no subtitle
        // stream at all (confirmed via ffprobe). Missing captions is a normal, expected case,
        // not a tool failure.
        var extractor = new CaptionExtractor();
        var fixturePath = GetCapturedFixturePath("sample-live-capture.ts");
        Assert.True(File.Exists(fixturePath), $"Real capture fixture not found: {fixturePath}");

        // Act
        var samples = await extractor.ExtractAsync(fixturePath, CancellationToken.None);

        // Assert
        Assert.Empty(samples);
    }

    [Fact]
    public async Task ExtractAsync_MissingFile_ThrowsInvalidOperationException()
    {
        // Arrange: a missing input file is a genuine tool failure (ffmpeg can't open it at all),
        // distinct from the "file exists but has no subtitle stream" case above -- it must not
        // be silently swallowed to an empty list.
        var extractor = new CaptionExtractor();
        var missingPath = Path.Combine(Path.GetTempPath(), $"missing-{Guid.NewGuid()}.mp4");

        // Act & Assert
        await Assert.ThrowsAsync<InvalidOperationException>(
            () => extractor.ExtractAsync(missingPath, CancellationToken.None));
    }

    [Fact]
    public async Task ExtractAsync_HungProcess_IsBoundedByConfiguredTimeout()
    {
        // Arrange: point ffmpegPath at the shared hung-process test double (see
        // TransportStreamInspectorTests.InspectAsync_HungProcess_IsBoundedByConfiguredTimeout
        // for why a real hang, not just fast real media, is what actually exercises this).
        var scriptPath = Path.Combine(AppContext.BaseDirectory, "hanging-ffmpeg.sh");
        var extractor = new CaptionExtractor(ffmpegPath: scriptPath, timeout: TimeSpan.FromMilliseconds(300));

        var sw = System.Diagnostics.Stopwatch.StartNew();

        await Assert.ThrowsAnyAsync<OperationCanceledException>(
            () => extractor.ExtractAsync("irrelevant-path", CancellationToken.None));

        sw.Stop();

        Assert.True(sw.ElapsedMilliseconds < 3000,
            $"Expected ExtractAsync to honor its ~300ms timeout against a hung process, took {sw.ElapsedMilliseconds}ms");
    }

    [Fact]
    public async Task ExtractAsync_CallerCancellation_ThrowsOperationCanceledExceptionPromptly()
    {
        // Arrange: same hung-process double, but bound by a very generous extractor timeout so
        // the CALLER's own token is what actually cuts it off, not the extractor's internal one.
        var scriptPath = Path.Combine(AppContext.BaseDirectory, "hanging-ffmpeg.sh");
        var extractor = new CaptionExtractor(ffmpegPath: scriptPath, timeout: TimeSpan.FromSeconds(30));
        using var cts = new CancellationTokenSource();
        cts.CancelAfter(TimeSpan.FromMilliseconds(200));

        var sw = System.Diagnostics.Stopwatch.StartNew();

        await Assert.ThrowsAnyAsync<OperationCanceledException>(
            () => extractor.ExtractAsync("irrelevant-path", cts.Token));

        sw.Stop();

        Assert.True(sw.ElapsedMilliseconds < 3000,
            $"Expected caller cancellation (~200ms) to cut off ExtractAsync promptly, took {sw.ElapsedMilliseconds}ms");
    }
}
