namespace SmartTVRelay.Core.Tests.Ingest;

using SmartTVRelay.Core;
using SmartTVRelay.Core.Ingest;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using Xunit;

public class Scte35MarkerExtractorTests
{
    private readonly Scte35MarkerExtractor _extractor = new();

    /// <summary>Fixture file path using AppContext.BaseDirectory for test output directory.</summary>
    private static string GetFixturePath(string filename)
    {
        return Path.Combine(AppContext.BaseDirectory, "synthetic", filename);
    }

    [Fact]
    public void Extract_WithSyntheticFixture_ReturnsExactlyOneCueOutAndOneCueIn()
    {
        // Arrange: fixtures/synthetic/scte35-sample.ts is generated by
        // fixtures/synthetic/generate-scte35-fixture.cs, encoding a CueOut at pts_time=90000
        // (1.0s) and a CueIn at pts_time=180000 (2.0s), both verified by hand against the
        // real ANSI/SCTE 35 splice_time() bit layout (see docs/scte35-findings.md).
        var fixturePath = GetFixturePath("scte35-sample.ts");
        Assert.True(File.Exists(fixturePath), $"Fixture file not found: {fixturePath}");

        // Act
        var signals = _extractor.Extract(fixturePath, CancellationToken.None);

        // Assert: exactly the two encoded events, with the correct kind and timestamp each --
        // not just "didn't throw" (an earlier version of this test only asserted non-null,
        // which passes even if extraction found nothing at all).
        Assert.Equal(2, signals.Count);

        var cueOut = Assert.Single(signals, s => s.Kind == ExplicitMarkerKind.CueOut);
        Assert.Equal(DateTimeOffset.UnixEpoch + TimeSpan.FromSeconds(1.0), cueOut.ObservedAt);

        var cueIn = Assert.Single(signals, s => s.Kind == ExplicitMarkerKind.CueIn);
        Assert.Equal(DateTimeOffset.UnixEpoch + TimeSpan.FromSeconds(2.0), cueIn.ObservedAt);
    }

    [Fact]
    public void Extract_HandCraftedSpecCompliantSection_DecodesCorrectPtsTime()
    {
        // Arrange: an independent oracle, built directly in this test rather than via the
        // shared fixture generator, so a bug shared between the generator and the parser
        // (which is exactly what an earlier version of this extractor had -- both consumed 6
        // bytes for splice_time() with PES-style marker bits instead of the spec's 5-byte,
        // marker-free encoding) cannot hide behind a self-consistent round trip.
        //
        // pts_time = 2,700,000 (30.0 seconds at 90kHz) = 0x0293E80, encoded per ANSI/SCTE 35
        // splice_time(): byte0 = time_specified_flag(1) + reserved(111111) + pts_time bit32(0),
        // followed by the remaining 32 bits of pts_time, big-endian, no marker bits.
        const uint ptsTime = 2_700_000; // 30.0s * 90000
        var filePath = Path.Combine(Path.GetTempPath(), $"scte35-oracle-{Guid.NewGuid()}.ts");

        try
        {
            WriteHandCraftedFixture(filePath, ptsTime);

            // Act
            var signals = _extractor.Extract(filePath, CancellationToken.None);

            // Assert
            var signal = Assert.Single(signals);
            Assert.Equal(ExplicitMarkerKind.CueOut, signal.Kind);
            Assert.Equal(DateTimeOffset.UnixEpoch + TimeSpan.FromSeconds(30.0), signal.ObservedAt);
        }
        finally
        {
            File.Delete(filePath);
        }
    }

    [Fact]
    public void Extract_NoScte35Pid_ReturnsEmptyList()
    {
        // Arrange: use the real HDHomeRun capture, which has video + 2 audio streams and no
        // SCTE-35/data PID at all (confirmed via ffprobe -- see docs/scte35-findings.md).
        var fixturePath = Path.Combine(AppContext.BaseDirectory, "captures", "sample-live-capture.ts");
        Assert.True(File.Exists(fixturePath), $"Real capture fixture not found: {fixturePath}");

        // Act
        var signals = _extractor.Extract(fixturePath, CancellationToken.None);

        // Assert
        Assert.Empty(signals);
    }

    [Fact]
    public void Extract_MalformedFile_ReturnsEmptyListWithoutThrowing()
    {
        // Arrange: a short garbage file with no valid TS sync bytes at all.
        var tempPath = Path.Combine(Path.GetTempPath(), $"malformed-{Guid.NewGuid()}.ts");
        File.WriteAllBytes(tempPath, new byte[] { 0x00, 0x01, 0x02, 0x03 });

        try
        {
            // Act
            var signals = _extractor.Extract(tempPath, CancellationToken.None);

            // Assert
            Assert.Empty(signals);
        }
        finally
        {
            File.Delete(tempPath);
        }
    }

    [Fact]
    public void Extract_MissingFile_ReturnsEmptyListWithoutThrowing()
    {
        // Arrange
        var missingPath = Path.Combine(Path.GetTempPath(), $"missing-{Guid.NewGuid()}.ts");

        // Act
        var signals = _extractor.Extract(missingPath, CancellationToken.None);

        // Assert
        Assert.Empty(signals);
    }

    /// <summary>
    /// Hand-builds a single-program MPEG-TS file (PAT -> PMT -> one SCTE-35 splice_insert
    /// CueOut section) independently of fixtures/synthetic/generate-scte35-fixture.cs, encoding
    /// every bit-packed field directly from the ANSI/SCTE 35 and ISO/IEC 13818-1 specs rather
    /// than reusing any shared helper, so this test cannot pass merely because it agrees with
    /// itself.
    /// </summary>
    private static void WriteHandCraftedFixture(string filePath, uint ptsTime)
    {
        const int patPid = 0x0000;
        const int pmtPid = 0x0200;
        const int scte35Pid = 0x0201;

        using var fs = new FileStream(filePath, FileMode.Create, FileAccess.Write);
        var writer = new BinaryWriter(fs);

        // PAT: table_id(0x00), section_length=13, program 1 -> pmtPid.
        var pat = new byte[]
        {
            0x00,                                                    // table_id
            0xB0, 0x0D,                                               // section_syntax_indicator=1, section_length=13
            0x00, 0x01,                                               // transport_stream_id
            0xC1, 0x00, 0x00,                                         // version/current_next, section_number, last_section_number
            0x00, 0x01,                                               // program_number = 1
            (byte)(0xE0 | ((pmtPid >> 8) & 0x1F)), (byte)(pmtPid & 0xFF), // reserved + PMT PID
            0x00, 0x00, 0x00, 0x00,                                   // CRC_32 (unvalidated)
        };
        WriteSection(writer, patPid, pat);

        // PMT: table_id(0x02), one elementary stream, stream_type=0x86 (SCTE-35) at scte35Pid.
        var pmt = new byte[]
        {
            0x02,                                                     // table_id
            0xB0, 0x12,                                                // section_length=18
            0x00, 0x01,                                                // program_number = 1
            0xC1, 0x00, 0x00,                                          // version/current_next, section_number, last_section_number
            0xE0, 0x00,                                                // reserved + PCR_PID (unused)
            0xF0, 0x00,                                                // reserved + program_info_length = 0
            0x86,                                                      // stream_type: SCTE-35
            (byte)(0xE0 | ((scte35Pid >> 8) & 0x1F)), (byte)(scte35Pid & 0xFF), // reserved + elementary_PID
            0xF0, 0x00,                                                // reserved + ES_info_length = 0
            0x00, 0x00, 0x00, 0x00,                                    // CRC_32 (unvalidated)
        };
        WriteSection(writer, pmtPid, pmt);

        // splice_insert(): splice_event_id=1, out_of_network_indicator=1 (CueOut),
        // program_splice_flag=1, splice_immediate_flag=0, splice_time present.
        byte ptsByte0 = (byte)(0x80 | 0x7E | ((ptsTime >> 32) & 0x01));
        var spliceInsert = new byte[]
        {
            0x00, 0x00, 0x00, 0x01,          // splice_event_id
            0x60,                             // cancel=0, out_of_network=1, program_splice=1, immediate=0
            ptsByte0,
            (byte)((ptsTime >> 24) & 0xFF),
            (byte)((ptsTime >> 16) & 0xFF),
            (byte)((ptsTime >> 8) & 0xFF),
            (byte)(ptsTime & 0xFF),
        };

        var spliceCommand = new byte[1 + spliceInsert.Length];
        spliceCommand[0] = 0x05; // splice_command_type: splice_insert
        Array.Copy(spliceInsert, 0, spliceCommand, 1, spliceInsert.Length);

        int spliceCommandLength = spliceCommand.Length;
        var scte35Body = new List<byte>
        {
            0x00,                             // protocol_version
            0x00, 0x00, 0x00, 0x00, 0x00,      // encrypted_packet+algorithm+pts_adjustment (5 bytes, unused)
            0x00,                              // cw_index
            0xFF,                              // tier high byte (reserved, all 1s)
            (byte)(0xF0 | ((spliceCommandLength >> 8) & 0x0F)), // tier low nibble + cmd_length high nibble
            (byte)(spliceCommandLength & 0xFF),                 // cmd_length low byte
        };
        scte35Body.AddRange(spliceCommand);
        scte35Body.AddRange(new byte[] { 0x00, 0x00, 0x00, 0x00 }); // CRC_32 (unvalidated)

        int sectionLength = scte35Body.Count;
        var scte35Section = new List<byte>
        {
            0xFC, // table_id: splice_info_section
            (byte)(0xB0 | ((sectionLength >> 8) & 0x0F)),
            (byte)(sectionLength & 0xFF),
        };
        scte35Section.AddRange(scte35Body);

        WriteSection(writer, scte35Pid, scte35Section.ToArray());

        writer.Flush();
    }

    private static void WriteSection(BinaryWriter writer, int pid, byte[] section)
    {
        const int tsPacketSize = 188;

        var payload = new byte[section.Length + 1];
        payload[0] = 0x00; // pointer_field: section begins immediately after this byte.
        Array.Copy(section, 0, payload, 1, section.Length);

        var packet = new byte[tsPacketSize];
        packet[0] = 0x47; // sync byte

        ushort pidField = (ushort)((pid & 0x1FFF) | 0x4000); // payload_unit_start_indicator=1
        packet[1] = (byte)((pidField >> 8) & 0xFF);
        packet[2] = (byte)(pidField & 0xFF);
        packet[3] = 0x10; // adaptation_field_control=01 (payload only), continuity_counter=0

        int payloadSize = Math.Min(payload.Length, tsPacketSize - 4);
        Array.Copy(payload, 0, packet, 4, payloadSize);

        writer.Write(packet);
    }
}
