namespace SmartTVRelay.Core.Tests.Ingest;

using SmartTVRelay.Core;
using SmartTVRelay.Core.Ingest;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using Xunit;

public class Scte35MarkerExtractorTests
{
    private readonly Scte35MarkerExtractor _extractor = new();

    /// <summary>Fixture file path using AppContext.BaseDirectory for test output directory.</summary>
    private static string GetFixturePath(string filename)
    {
        return Path.Combine(AppContext.BaseDirectory, "synthetic", filename);
    }

    [Fact]
    public void Extract_WithSyntheticFixture_ReturnsExactlyOneCueOutAndOneCueIn()
    {
        // Arrange: fixtures/synthetic/scte35-sample.ts is generated by
        // fixtures/synthetic/generate-scte35-fixture.cs, encoding a CueOut at pts_time=90000
        // (1.0s) and a CueIn at pts_time=180000 (2.0s), both verified by hand against the
        // real ANSI/SCTE 35 splice_time() bit layout (see docs/scte35-findings.md).
        var fixturePath = GetFixturePath("scte35-sample.ts");
        Assert.True(File.Exists(fixturePath), $"Fixture file not found: {fixturePath}");

        // Act
        var signals = _extractor.Extract(fixturePath, CancellationToken.None);

        // Assert: exactly the two encoded events, with the correct kind and timestamp each --
        // not just "didn't throw" (an earlier version of this test only asserted non-null,
        // which passes even if extraction found nothing at all).
        Assert.Equal(2, signals.Count);

        var cueOut = Assert.Single(signals, s => s.Kind == ExplicitMarkerKind.CueOut);
        Assert.Equal(DateTimeOffset.UnixEpoch + TimeSpan.FromSeconds(1.0), cueOut.ObservedAt);

        var cueIn = Assert.Single(signals, s => s.Kind == ExplicitMarkerKind.CueIn);
        Assert.Equal(DateTimeOffset.UnixEpoch + TimeSpan.FromSeconds(2.0), cueIn.ObservedAt);
    }

    [Theory]
    [InlineData("scte35-time-signal-202-36.ts", ExplicitMarkerKind.CueOut, 7_107_207_073L)]
    [InlineData("scte35-time-signal-203-36.ts", ExplicitMarkerKind.CueOut, 7_122_089_941L)]
    [InlineData("scte35-time-signal-203-37.ts", ExplicitMarkerKind.CueIn, 7_123_441_291L)]
    public void Extract_RealIssue124TimeSignalFixture_UsesHandDecodedOracle(string filename, ExplicitMarkerKind expectedKind, long expectedPts)
    {
        // The section bytes are copied verbatim from issue #124. The expected PTS values below
        // were decoded independently from the spec's time_signal splice_time: low bit of its
        // first byte followed by four big-endian bytes; pts_adjustment is zero in all three.
        var signals = _extractor.Extract(GetFixturePath(filename));
        var signal = Assert.Single(signals);
        Assert.Equal(expectedKind, signal.Kind);
        Assert.Equal(DateTimeOffset.UnixEpoch + TimeSpan.FromSeconds(expectedPts / 90_000.0), signal.ObservedAt);
    }

    [Fact]
    public void Extract_TimeSignalSegmentationCancelAndUnknownType_AreIgnored()
    {
        var filePath = Path.Combine(Path.GetTempPath(), $"scte35-time-cancel-{Guid.NewGuid()}.ts");
        try
        {
            WriteHandCraftedTimeSignalFixture(filePath, segmentationEventId: 0x203, segmentationType: 0x36,
                canceled: true);
            Assert.Empty(_extractor.Extract(filePath));
            WriteHandCraftedTimeSignalFixture(filePath, segmentationEventId: 0x203, segmentationType: 0x99);
            Assert.Empty(_extractor.Extract(filePath));
        }
        finally { File.Delete(filePath); }
    }

    [Fact]
    public void Extract_TruncatedTimeSignalSection_ReturnsEmpty()
    {
        var filePath = Path.Combine(Path.GetTempPath(), $"scte35-time-truncated-{Guid.NewGuid()}.ts");
        try
        {
            // Complete PSI framing, but the SCTE-35 section declares bytes beyond its supplied body.
            using var fs = new FileStream(filePath, FileMode.Create, FileAccess.Write);
            using var writer = new BinaryWriter(fs);
            WriteSection(writer, 0x0000, BuildPatSection(0x0200));
            WriteSection(writer, 0x0200, BuildPmtSection(0x0201));
            WriteSection(writer, 0x0201, new byte[] { 0xFC, 0xB0, 0x2D, 0x00, 0x00, 0x00 });
            writer.Flush();
            Assert.Empty(_extractor.Extract(filePath));
        }
        finally { File.Delete(filePath); }
    }

    private static void WriteHandCraftedTimeSignalFixture(string filePath, uint segmentationEventId, byte segmentationType, bool canceled = false)
    {
        // Independent test oracle layout from ANSI/SCTE 35: time_signal command 0x06,
        // specified PTS 90000 in five bytes, descriptor_loop_length, tag/length, CUEI,
        // event ID, cancel byte, program/duration/delivery flags, UPID, type, segment counters.
        byte[] descriptor = { 0x02, 0x14, 0x43, 0x55, 0x45, 0x49,
            (byte)(segmentationEventId >> 24), (byte)(segmentationEventId >> 16), (byte)(segmentationEventId >> 8), (byte)segmentationEventId,
            (byte)(canceled ? 0x80 : 0x00), 0xE0, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, segmentationType, 0x00, 0x01 };
        // The uncanceled descriptor includes duration, an empty UPID, type, and segment counters.
        if (canceled) descriptor = descriptor[..11];
        descriptor[1] = (byte)(descriptor.Length - 2);
        var section = new List<byte> { 0xFC, 0xB0, 0x00, 0x00, 0, 0, 0, 0, 0, 0, 0x00, 0xFF, 0xF0, 0x06,
            0x06, 0x80, 0x00, 0x01, 0x5F, 0x90, (byte)(descriptor.Length >> 8), (byte)descriptor.Length };
        section.AddRange(descriptor);
        section.AddRange(new byte[] { 0, 0, 0, 0 });
        int sectionLength = section.Count - 3;
        section[1] = (byte)(0xB0 | (sectionLength >> 8)); section[2] = (byte)sectionLength;
        using var fs = new FileStream(filePath, FileMode.Create, FileAccess.Write);
        using var writer = new BinaryWriter(fs);
        WriteSection(writer, 0, BuildPatSection(0x0200));
        WriteSection(writer, 0x0200, BuildPmtSection(0x0201));
        WriteSection(writer, 0x0201, section.ToArray());
        writer.Flush();
    }

    [Fact]
    public void Extract_HandCraftedSpecCompliantSection_DecodesCorrectPtsTime()
    {
        // Arrange: an independent oracle, built directly in this test rather than via the
        // shared fixture generator, so a bug shared between the generator and the parser
        // (which is exactly what an earlier version of this extractor had -- both consumed 6
        // bytes for splice_time() with PES-style marker bits instead of the spec's 5-byte,
        // marker-free encoding) cannot hide behind a self-consistent round trip.
        //
        // pts_time = 2,700,000 (30.0 seconds at 90kHz) = 0x0293E80, encoded per ANSI/SCTE 35
        // splice_time(): byte0 = time_specified_flag(1) + reserved(111111) + pts_time bit32(0),
        // followed by the remaining 32 bits of pts_time, big-endian, no marker bits.
        const uint ptsTime = 2_700_000; // 30.0s * 90000
        var filePath = Path.Combine(Path.GetTempPath(), $"scte35-oracle-{Guid.NewGuid()}.ts");

        try
        {
            WriteHandCraftedFixture(filePath, ptsTime);

            // Act
            var signals = _extractor.Extract(filePath, CancellationToken.None);

            // Assert
            var signal = Assert.Single(signals);
            Assert.Equal(ExplicitMarkerKind.CueOut, signal.Kind);
            Assert.Equal(DateTimeOffset.UnixEpoch + TimeSpan.FromSeconds(30.0), signal.ObservedAt);
        }
        finally
        {
            File.Delete(filePath);
        }
    }

    [Fact]
    public void Extract_NoScte35Pid_ReturnsEmptyList()
    {
        // Arrange: use the real HDHomeRun capture, which has video + 2 audio streams and no
        // SCTE-35/data PID at all (confirmed via ffprobe -- see docs/scte35-findings.md).
        var fixturePath = Path.Combine(AppContext.BaseDirectory, "captures", "sample-live-capture.ts");
        Assert.True(File.Exists(fixturePath), $"Real capture fixture not found: {fixturePath}");

        // Act
        var signals = _extractor.Extract(fixturePath, CancellationToken.None);

        // Assert
        Assert.Empty(signals);
    }

    [Fact]
    public void Extract_MalformedFile_ReturnsEmptyListWithoutThrowing()
    {
        // Arrange: a short garbage file with no valid TS sync bytes at all.
        var tempPath = Path.Combine(Path.GetTempPath(), $"malformed-{Guid.NewGuid()}.ts");
        File.WriteAllBytes(tempPath, new byte[] { 0x00, 0x01, 0x02, 0x03 });

        try
        {
            // Act
            var signals = _extractor.Extract(tempPath, CancellationToken.None);

            // Assert
            Assert.Empty(signals);
        }
        finally
        {
            File.Delete(tempPath);
        }
    }

    [Fact]
    public void Extract_MissingFile_ReturnsEmptyListWithoutThrowing()
    {
        // Arrange
        var missingPath = Path.Combine(Path.GetTempPath(), $"missing-{Guid.NewGuid()}.ts");

        // Act
        var signals = _extractor.Extract(missingPath, CancellationToken.None);

        // Assert
        Assert.Empty(signals);
    }

    [Fact]
    public void Extract_ImmediateSplice_EmitsNoSignal()
    {
        // Arrange: splice_immediate_flag=1 means no splice_time() is present in the section at
        // all. Extract() only parses recorded files, so wall-clock "now" at parse time has no
        // relationship to broadcast time -- the extractor must emit nothing here rather than a
        // fabricated, wrongly-timed signal (see docs/scte35-findings.md, "Known Limitations" #5).
        var filePath = Path.Combine(Path.GetTempPath(), $"scte35-immediate-{Guid.NewGuid()}.ts");

        try
        {
            WriteHandCraftedFixture(filePath, ptsTime: 0, immediate: true);

            // Act
            var signals = _extractor.Extract(filePath, CancellationToken.None);

            // Assert
            Assert.Empty(signals);
        }
        finally
        {
            File.Delete(filePath);
        }
    }

    [Fact]
    public void Extract_UnspecifiedSpliceTime_EmitsNoSignal()
    {
        // Arrange: time_specified_flag=0 means splice_time() carries no pts_time either --
        // same rationale as the immediate-splice case above.
        var filePath = Path.Combine(Path.GetTempPath(), $"scte35-unspecified-{Guid.NewGuid()}.ts");

        try
        {
            WriteHandCraftedFixture(filePath, ptsTime: 0, timeSpecified: false);

            // Act
            var signals = _extractor.Extract(filePath, CancellationToken.None);

            // Assert
            Assert.Empty(signals);
        }
        finally
        {
            File.Delete(filePath);
        }
    }

    [Fact]
    public void Extract_WithPtsAdjustment_AppliesItToTheObservedTime()
    {
        // Arrange: pts_adjustment is a real, independently-encoded field (data[4..8] of the
        // splice_info_section header) that must be added to pts_time -- effective time is
        // (pts_time + pts_adjustment) mod 2^33, per ANSI/SCTE 35. pts_time=90000 (1.0s) with
        // pts_adjustment=90000 (1.0s) should observe at 2.0s, not 1.0s.
        const uint ptsTime = 90_000;
        const uint ptsAdjustment = 90_000;
        var filePath = Path.Combine(Path.GetTempPath(), $"scte35-adjustment-{Guid.NewGuid()}.ts");

        try
        {
            WriteHandCraftedFixture(filePath, ptsTime, ptsAdjustment: ptsAdjustment);

            // Act
            var signals = _extractor.Extract(filePath, CancellationToken.None);

            // Assert
            var signal = Assert.Single(signals);
            Assert.Equal(DateTimeOffset.UnixEpoch + TimeSpan.FromSeconds(2.0), signal.ObservedAt);
        }
        finally
        {
            File.Delete(filePath);
        }
    }

    [Fact]
    public void Extract_TwoSectionsPackedInOnePacket_ReturnsBothSignals()
    {
        // Arrange: a CueOut and a CueIn splice_insert, small enough to both fit in one TS
        // packet's 184-byte payload, packed together (real broadcast encoders can and do pack
        // multiple small PSI sections into a single packet). An earlier version of
        // ScanSectionsForPid accumulated the whole payload as a single blob and invoked
        // onSection only once per payload_unit_start boundary, so the second section here would
        // have been silently dropped.
        const int patPid = 0x0000;
        const int pmtPid = 0x0200;
        const int scte35Pid = 0x0201;
        var filePath = Path.Combine(Path.GetTempPath(), $"scte35-packed-{Guid.NewGuid()}.ts");

        try
        {
            using (var fs = new FileStream(filePath, FileMode.Create, FileAccess.Write))
            {
                var writer = new BinaryWriter(fs);
                WriteSection(writer, patPid, BuildPatSection(pmtPid));
                WriteSection(writer, pmtPid, BuildPmtSection(scte35Pid));

                var cueOut = BuildSpliceInsertSection(eventId: 1, cueOut: true, ptsTime: 90_000);
                var cueIn = BuildSpliceInsertSection(eventId: 2, cueOut: false, ptsTime: 180_000);
                WriteSections(writer, scte35Pid, cueOut, cueIn);

                writer.Flush();
            }

            // Act
            var signals = _extractor.Extract(filePath, CancellationToken.None);

            // Assert
            Assert.Equal(2, signals.Count);
            var actualCueOut = Assert.Single(signals, s => s.Kind == ExplicitMarkerKind.CueOut);
            Assert.Equal(DateTimeOffset.UnixEpoch + TimeSpan.FromSeconds(1.0), actualCueOut.ObservedAt);
            var actualCueIn = Assert.Single(signals, s => s.Kind == ExplicitMarkerKind.CueIn);
            Assert.Equal(DateTimeOffset.UnixEpoch + TimeSpan.FromSeconds(2.0), actualCueIn.ObservedAt);
        }
        finally
        {
            File.Delete(filePath);
        }
    }

    [Fact]
    public void Extract_CanceledEvent_ExcludesItFromReturnedSignals()
    {
        // Arrange: a CueOut is announced for event_id=1, then later canceled by a second
        // splice_insert with the same event_id and splice_event_cancel_indicator=1. The
        // canceled CueOut must not appear in the returned signals -- an earlier version ignored
        // the cancellation entirely and left the already-parsed CueOut in the list, which would
        // expose a real cancellation as high-confidence commercial evidence.
        const int patPid = 0x0000;
        const int pmtPid = 0x0200;
        const int scte35Pid = 0x0201;
        var filePath = Path.Combine(Path.GetTempPath(), $"scte35-canceled-{Guid.NewGuid()}.ts");

        try
        {
            using (var fs = new FileStream(filePath, FileMode.Create, FileAccess.Write))
            {
                var writer = new BinaryWriter(fs);
                WriteSection(writer, patPid, BuildPatSection(pmtPid));
                WriteSection(writer, pmtPid, BuildPmtSection(scte35Pid));
                WriteSection(writer, scte35Pid, BuildSpliceInsertSection(eventId: 1, cueOut: true, ptsTime: 90_000));
                WriteSection(writer, scte35Pid, BuildSpliceInsertSection(eventId: 1, cueOut: true, ptsTime: 0, cancel: true));

                writer.Flush();
            }

            // Act
            var signals = _extractor.Extract(filePath, CancellationToken.None);

            // Assert
            Assert.Empty(signals);
        }
        finally
        {
            File.Delete(filePath);
        }
    }

    [Fact]
    public void Extract_AlreadyCanceledToken_ThrowsOperationCanceledExceptionRatherThanReturningPartialResults()
    {
        // Arrange: caller cancellation must be observable, not silently turned into a
        // "successful" (partial or empty) result by the broad catch that handles genuine parsing
        // errors -- an earlier version caught OperationCanceledException too, along with every
        // other exception type, and returned whatever had been parsed so far as if it were a
        // normal, complete result.
        var filePath = Path.Combine(Path.GetTempPath(), $"scte35-canceled-token-{Guid.NewGuid()}.ts");

        try
        {
            WriteHandCraftedFixture(filePath, ptsTime: 90_000);
            using var cts = new CancellationTokenSource();
            cts.Cancel();

            // Act & Assert
            Assert.ThrowsAny<OperationCanceledException>(() => _extractor.Extract(filePath, cts.Token));
        }
        finally
        {
            File.Delete(filePath);
        }
    }

    [Fact]
    public void Extract_TransportErrorIndicatorSet_DiscardsCorruptedPacketWithoutEmittingSignal()
    {
        // Arrange: a corrupted, non-payload-unit-start packet on the SCTE-35 PID with
        // transport_error_indicator set, carrying what looks like a complete, self-contained
        // splice_insert section (event_id=99, a deliberately distinctive bogus pts_time) right
        // at its payload start -- the same shape as a genuine continuation packet. Per
        // ISO/IEC 13818-1, transport_error_indicator means at least one uncorrectable bit error
        // is present in this packet, so nothing in its payload can be trusted; an earlier
        // version of ScanSectionsForPid did not check this bit at all and would have appended
        // and parsed this bogus section as a spurious extra signal.
        const int patPid = 0x0000;
        const int pmtPid = 0x0200;
        const int scte35Pid = 0x0201;
        var filePath = Path.Combine(Path.GetTempPath(), $"scte35-tei-{Guid.NewGuid()}.ts");

        try
        {
            using (var fs = new FileStream(filePath, FileMode.Create, FileAccess.Write))
            {
                var writer = new BinaryWriter(fs);
                WriteSection(writer, patPid, BuildPatSection(pmtPid));
                WriteSection(writer, pmtPid, BuildPmtSection(scte35Pid));
                WriteSection(writer, scte35Pid, BuildSpliceInsertSection(eventId: 1, cueOut: true, ptsTime: 90_000));

                var bogusSection = BuildSpliceInsertSection(eventId: 99, cueOut: false, ptsTime: 999_000);
                WriteRawPacket(writer, scte35Pid, payloadUnitStart: false, transportErrorIndicator: true, bogusSection);

                WriteSection(writer, scte35Pid, BuildSpliceInsertSection(eventId: 2, cueOut: false, ptsTime: 180_000));

                writer.Flush();
            }

            // Act
            var signals = _extractor.Extract(filePath, CancellationToken.None);

            // Assert: exactly the two genuine events -- the corrupted packet's bogus event_id=99
            // at ~11.1s must not appear at all, whether as a spurious third signal or in place of
            // the genuine CueIn.
            Assert.Equal(2, signals.Count);
            var cueOut = Assert.Single(signals, s => s.Kind == ExplicitMarkerKind.CueOut);
            Assert.Equal(DateTimeOffset.UnixEpoch + TimeSpan.FromSeconds(1.0), cueOut.ObservedAt);
            var cueIn = Assert.Single(signals, s => s.Kind == ExplicitMarkerKind.CueIn);
            Assert.Equal(DateTimeOffset.UnixEpoch + TimeSpan.FromSeconds(2.0), cueIn.ObservedAt);
        }
        finally
        {
            File.Delete(filePath);
        }
    }

    [Fact]
    public void Extract_IncompleteSectionAtBoundary_StillParsesFollowingSectionCorrectly()
    {
        // Arrange: simulates lost/never-sent continuation packets. The first packet on the
        // SCTE-35 PID starts a section that declares a total length (203 bytes) far larger than
        // what a single TS packet can carry (183 bytes of section data after the pointer_field),
        // and no continuation packets for it ever arrive -- the next packet on this PID jumps
        // straight to a brand-new, complete, genuine section. Per the class's own documented
        // reasoning, that stale, never-completed fragment must be discarded at the new section's
        // payload_unit_start boundary rather than left in the buffer: an earlier version left it
        // there, so the genuine section's real bytes got appended after it and the whole thing
        // sat forever waiting for a length that could never be satisfied, silently losing the
        // genuine signal.
        const int patPid = 0x0000;
        const int pmtPid = 0x0200;
        const int scte35Pid = 0x0201;
        var filePath = Path.Combine(Path.GetTempPath(), $"scte35-incomplete-boundary-{Guid.NewGuid()}.ts");

        try
        {
            using (var fs = new FileStream(filePath, FileMode.Create, FileAccess.Write))
            {
                var writer = new BinaryWriter(fs);
                WriteSection(writer, patPid, BuildPatSection(pmtPid));
                WriteSection(writer, pmtPid, BuildPmtSection(scte35Pid));

                // Stale, never-completed section: pointer_field(1) + table_id+section_length(3,
                // declaring 200 more bytes than present) + 180 bytes of filler = 184 bytes,
                // exactly filling one TS packet's payload with no room left for the section to
                // ever actually complete from this packet alone, and no continuation follows.
                var stalePayload = new byte[184];
                stalePayload[0] = 0x00; // pointer_field
                stalePayload[1] = 0xFC; // table_id (SCTE-35, irrelevant -- never parsed)
                stalePayload[2] = 0xB0; // section_length high nibble (declared length=200)
                stalePayload[3] = 0xC8;
                for (int i = 4; i < stalePayload.Length; i++)
                {
                    stalePayload[i] = 0xAA; // arbitrary filler, distinct from 0xFF stuffing
                }

                WriteRawPacket(writer, scte35Pid, payloadUnitStart: true, transportErrorIndicator: false, stalePayload);

                // A brand-new, genuine, complete section immediately follows -- unrelated to the
                // stale fragment above.
                WriteSection(writer, scte35Pid, BuildSpliceInsertSection(eventId: 1, cueOut: false, ptsTime: 180_000));

                writer.Flush();
            }

            // Act
            var signals = _extractor.Extract(filePath, CancellationToken.None);

            // Assert
            var signal = Assert.Single(signals);
            Assert.Equal(ExplicitMarkerKind.CueIn, signal.Kind);
            Assert.Equal(DateTimeOffset.UnixEpoch + TimeSpan.FromSeconds(2.0), signal.ObservedAt);
        }
        finally
        {
            File.Delete(filePath);
        }
    }

    [Fact]
    public void Extract_PatCurrentNextIndicatorZero_ReturnsEmptyList()
    {
        // Arrange: current_next_indicator=0 (data[5] bit0) marks this PAT as describing a
        // not-yet-active table version (e.g. mid version transition) -- ISO/IEC 13818-1. It must
        // be ignored rather than followed, since the PMT PID it lists may not be the one
        // actually carrying SCTE-35 data yet.
        const int patPid = 0x0000;
        const int pmtPid = 0x0200;
        const int scte35Pid = 0x0201;
        var filePath = Path.Combine(Path.GetTempPath(), $"scte35-pat-not-current-{Guid.NewGuid()}.ts");

        try
        {
            using (var fs = new FileStream(filePath, FileMode.Create, FileAccess.Write))
            {
                var writer = new BinaryWriter(fs);
                WriteSection(writer, patPid, BuildPatSection(pmtPid, currentNextIndicator: false));
                WriteSection(writer, pmtPid, BuildPmtSection(scte35Pid));
                WriteSection(writer, scte35Pid, BuildSpliceInsertSection(eventId: 1, cueOut: true, ptsTime: 90_000));

                writer.Flush();
            }

            // Act
            var signals = _extractor.Extract(filePath, CancellationToken.None);

            // Assert
            Assert.Empty(signals);
        }
        finally
        {
            File.Delete(filePath);
        }
    }

    [Fact]
    public void Extract_PmtCurrentNextIndicatorZero_ReturnsEmptyList()
    {
        // Arrange: same rationale as the PAT case above, applied to the PMT's own
        // current_next_indicator (also data[5] bit0, per the PMT's own layout).
        const int patPid = 0x0000;
        const int pmtPid = 0x0200;
        const int scte35Pid = 0x0201;
        var filePath = Path.Combine(Path.GetTempPath(), $"scte35-pmt-not-current-{Guid.NewGuid()}.ts");

        try
        {
            using (var fs = new FileStream(filePath, FileMode.Create, FileAccess.Write))
            {
                var writer = new BinaryWriter(fs);
                WriteSection(writer, patPid, BuildPatSection(pmtPid));
                WriteSection(writer, pmtPid, BuildPmtSection(scte35Pid, currentNextIndicator: false));
                WriteSection(writer, scte35Pid, BuildSpliceInsertSection(eventId: 1, cueOut: true, ptsTime: 90_000));

                writer.Flush();
            }

            // Act
            var signals = _extractor.Extract(filePath, CancellationToken.None);

            // Assert
            Assert.Empty(signals);
        }
        finally
        {
            File.Delete(filePath);
        }
    }

    private static byte[] BuildPatSection(int pmtPid, bool currentNextIndicator = true) => new byte[]
    {
        0x00,                                                       // table_id
        0xB0, 0x0D,                                                  // section_length=13
        0x00, 0x01,                                                  // transport_stream_id
        (byte)(currentNextIndicator ? 0xC1 : 0xC0), 0x00, 0x00,      // version/current_next, section_number, last_section_number
        0x00, 0x01,                                                  // program_number = 1
        (byte)(0xE0 | ((pmtPid >> 8) & 0x1F)), (byte)(pmtPid & 0xFF), // reserved + PMT PID
        0x00, 0x00, 0x00, 0x00,                                      // CRC_32 (unvalidated)
    };

    private static byte[] BuildPmtSection(int scte35Pid, bool currentNextIndicator = true) => new byte[]
    {
        0x02,                                                              // table_id
        0xB0, 0x12,                                                         // section_length=18
        0x00, 0x01,                                                         // program_number = 1
        (byte)(currentNextIndicator ? 0xC1 : 0xC0), 0x00, 0x00,             // version/current_next, section_number, last_section_number
        0xE0, 0x00,                                                         // reserved + PCR_PID (unused)
        0xF0, 0x00,                                                         // reserved + program_info_length = 0
        0x86,                                                               // stream_type: SCTE-35
        (byte)(0xE0 | ((scte35Pid >> 8) & 0x1F)), (byte)(scte35Pid & 0xFF), // reserved + elementary_PID
        0xF0, 0x00,                                                         // reserved + ES_info_length = 0
        0x00, 0x00, 0x00, 0x00,                                             // CRC_32 (unvalidated)
    };

    /// <summary>
    /// Hand-builds a single-program MPEG-TS file (PAT -> PMT -> one SCTE-35 splice_insert
    /// CueOut section) independently of fixtures/synthetic/generate-scte35-fixture.cs, encoding
    /// every bit-packed field directly from the ANSI/SCTE 35 and ISO/IEC 13818-1 specs rather
    /// than reusing any shared helper, so this test cannot pass merely because it agrees with
    /// itself.
    /// </summary>
    private static void WriteHandCraftedFixture(string filePath, uint ptsTime, uint ptsAdjustment = 0, bool immediate = false, bool timeSpecified = true)
    {
        const int patPid = 0x0000;
        const int pmtPid = 0x0200;
        const int scte35Pid = 0x0201;

        using var fs = new FileStream(filePath, FileMode.Create, FileAccess.Write);
        var writer = new BinaryWriter(fs);

        WriteSection(writer, patPid, BuildPatSection(pmtPid));
        WriteSection(writer, pmtPid, BuildPmtSection(scte35Pid));

        var scte35Section = BuildSpliceInsertSection(eventId: 1, cueOut: true, ptsTime: ptsTime, ptsAdjustment: ptsAdjustment, immediate: immediate, timeSpecified: timeSpecified);
        WriteSection(writer, scte35Pid, scte35Section);

        writer.Flush();
    }

    /// <summary>
    /// Builds one complete splice_info_section() containing one splice_insert() command, byte-exact
    /// per ANSI/SCTE 35. When <paramref name="cancel"/> is true, builds a cancellation for
    /// <paramref name="eventId"/> instead (splice_event_cancel_indicator=1; no flags/splice_time
    /// bytes follow, since none exist in that case).
    /// </summary>
    private static byte[] BuildSpliceInsertSection(uint eventId, bool cueOut, uint ptsTime, uint ptsAdjustment = 0, bool immediate = false, bool timeSpecified = true, bool cancel = false)
    {
        // splice_insert(): splice_event_id, out_of_network_indicator=<cueOut>,
        // program_splice_flag=1, splice_immediate_flag=<immediate>.
        // Per ANSI/SCTE 35, splice_event_cancel_indicator is its own byte (bit7 + 7 reserved
        // bits); out_of_network/program_splice/duration/immediate flags are the NEXT byte, present
        // only when splice_event_cancel_indicator=0. splice_time() is present only when
        // program_splice_flag=1 AND splice_immediate_flag=0; it is 1 byte when
        // time_specified_flag=0 (flag + 7 reserved bits, no pts_time), or 5 bytes when
        // time_specified_flag=1 (flag + 6 reserved bits + 33-bit pts_time, no marker bits).
        var spliceInsert = new List<byte>
        {
            (byte)((eventId >> 24) & 0xFF),
            (byte)((eventId >> 16) & 0xFF),
            (byte)((eventId >> 8) & 0xFF),
            (byte)(eventId & 0xFF),
        };

        if (cancel)
        {
            spliceInsert.Add(0x80); // splice_event_cancel_indicator=1, reserved(7)
        }
        else
        {
            spliceInsert.Add(0x00); // splice_event_cancel_indicator=0, reserved(7)

            byte flagsByte = (byte)((cueOut ? 0x80 : 0x00) | 0x40 | (immediate ? 0x10 : 0x00)); // out_of_network + program_splice=1 + immediate
            spliceInsert.Add(flagsByte);

            if (!immediate)
            {
                if (!timeSpecified)
                {
                    spliceInsert.Add(0x00); // time_specified_flag=0, reserved(7)
                }
                else
                {
                    byte ptsByte0 = (byte)(0x80 | 0x7E | ((ptsTime >> 32) & 0x01));
                    spliceInsert.Add(ptsByte0);
                    spliceInsert.Add((byte)((ptsTime >> 24) & 0xFF));
                    spliceInsert.Add((byte)((ptsTime >> 16) & 0xFF));
                    spliceInsert.Add((byte)((ptsTime >> 8) & 0xFF));
                    spliceInsert.Add((byte)(ptsTime & 0xFF));
                }
            }
        }

        var spliceCommand = new byte[1 + spliceInsert.Count];
        spliceCommand[0] = 0x05; // splice_command_type: splice_insert
        spliceInsert.CopyTo(spliceCommand, 1);

        // encrypted_packet(0) + encryption_algorithm(0) + pts_adjustment: same plain 33-bit
        // layout as splice_time()'s pts_time (no marker bits), sharing byte0's low bit as MSB.
        byte adjByte0 = (byte)((ptsAdjustment >> 32) & 0x01);
        var ptsAdjustmentBytes = new byte[]
        {
            adjByte0,
            (byte)((ptsAdjustment >> 24) & 0xFF),
            (byte)((ptsAdjustment >> 16) & 0xFF),
            (byte)((ptsAdjustment >> 8) & 0xFF),
            (byte)(ptsAdjustment & 0xFF),
        };

        int spliceCommandLength = spliceCommand.Length;
        var scte35Body = new List<byte>
        {
            0x00, // protocol_version
        };
        scte35Body.AddRange(ptsAdjustmentBytes); // encrypted_packet+algorithm+pts_adjustment (5 bytes)
        scte35Body.AddRange(new byte[]
        {
            0x00,                              // cw_index
            0xFF,                              // tier high byte (reserved, all 1s)
            (byte)(0xF0 | ((spliceCommandLength >> 8) & 0x0F)), // tier low nibble + cmd_length high nibble
            (byte)(spliceCommandLength & 0xFF),                 // cmd_length low byte
        });
        scte35Body.AddRange(spliceCommand);
        scte35Body.AddRange(new byte[] { 0x00, 0x00, 0x00, 0x00 }); // CRC_32 (unvalidated)

        int sectionLength = scte35Body.Count;
        var scte35Section = new List<byte>
        {
            0xFC, // table_id: splice_info_section
            (byte)(0xB0 | ((sectionLength >> 8) & 0x0F)),
            (byte)(sectionLength & 0xFF),
        };
        scte35Section.AddRange(scte35Body);

        return scte35Section.ToArray();
    }

    private static void WriteSection(BinaryWriter writer, int pid, byte[] section)
    {
        WriteSections(writer, pid, section);
    }

    /// <summary>
    /// Writes one or more complete sections packed into a single TS packet's payload (used to
    /// exercise the "two sections in one packet" path -- see
    /// Extract_TwoSectionsPackedInOnePacket_ReturnsBothSignals). The unused tail of the packet is
    /// filled with 0xFF stuffing bytes, per ISO/IEC 13818-1 2.4.4.7 -- not left as zero-initialized
    /// padding, which a spec-compliant demuxer cannot distinguish from the start of a genuine
    /// PAT-table_id (0x00) section with a bogus zero length, and would misinterpret as such.
    /// </summary>
    private static void WriteSections(BinaryWriter writer, int pid, params byte[][] sections)
    {
        const int tsPacketSize = 188;

        var payload = new List<byte> { 0x00 }; // pointer_field: first section begins right after this.
        foreach (var section in sections)
        {
            payload.AddRange(section);
        }

        var packet = new byte[tsPacketSize];
        packet[0] = 0x47; // sync byte

        ushort pidField = (ushort)((pid & 0x1FFF) | 0x4000); // payload_unit_start_indicator=1
        packet[1] = (byte)((pidField >> 8) & 0xFF);
        packet[2] = (byte)(pidField & 0xFF);
        packet[3] = 0x10; // adaptation_field_control=01 (payload only), continuity_counter=0

        int payloadSize = Math.Min(payload.Count, tsPacketSize - 4);
        for (int i = 0; i < tsPacketSize - 4; i++)
        {
            packet[4 + i] = i < payloadSize ? payload[i] : (byte)0xFF; // 0xFF stuffing past the real payload.
        }

        writer.Write(packet);
    }

    /// <summary>
    /// Writes one raw TS packet with full control over payload_unit_start_indicator and
    /// transport_error_indicator, for tests that need byte-exact control the higher-level
    /// <see cref="WriteSections"/> helper does not expose (e.g. simulating a corrupted or a
    /// deliberately non-payload-unit-start packet). <paramref name="payload"/> is copied
    /// starting right after the 4-byte TS header -- if the caller wants a payload_unit_start
    /// packet, it must include the pointer_field itself as the payload's first byte, matching
    /// real MPEG-TS framing (ISO/IEC 13818-1).
    /// </summary>
    private static void WriteRawPacket(BinaryWriter writer, int pid, bool payloadUnitStart, bool transportErrorIndicator, byte[] payload)
    {
        const int tsPacketSize = 188;

        var packet = new byte[tsPacketSize];
        packet[0] = 0x47; // sync byte

        ushort pidField = (ushort)(pid & 0x1FFF);
        if (payloadUnitStart)
        {
            pidField |= 0x4000;
        }

        packet[1] = (byte)((pidField >> 8) & 0xFF);
        if (transportErrorIndicator)
        {
            packet[1] |= 0x80;
        }

        packet[2] = (byte)(pidField & 0xFF);
        packet[3] = 0x10; // adaptation_field_control=01 (payload only), continuity_counter=0

        int payloadSize = Math.Min(payload.Length, tsPacketSize - 4);
        for (int i = 0; i < tsPacketSize - 4; i++)
        {
            packet[4 + i] = i < payloadSize ? payload[i] : (byte)0xFF; // 0xFF stuffing past the real payload.
        }

        writer.Write(packet);
    }
}
